# syntax=docker/dockerfile:1

ARG GO_VERSION=1.22

FROM --platform=$BUILDPLATFORM golang:${GO_VERSION}-alpine AS build
WORKDIR /src
ARG TARGETOS
ARG TARGETARCH
RUN --mount=type=bind,target=. \
GOOS=$TARGETOS GOARCH=$TARGETARCH go build -ldflags "-s -w" -o /usr/bin/app .

FROM alpine
COPY --from=build /usr/bin/app /usr/bin/app
CMD ["app"]
